databases:
  - name: poemsdb
    plan: free
    databaseName: poems
    user: anna  

services:
  - type: web
    plan: free
    name: poems
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn poems.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poemsdb
          property: "postgres://anna:2JDJwY3ZeybnVQpzWSD1O27BkGRvtW0Q@dpg-cnq6a50l6cac73ar3i6g-a/poems_85n6"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CORS_ALLOWED_ORIGINS
        value: "https://aipoems.netlify.app"
      - key: CORS_ALLOW_HEADERS
        value: "*"