# Generated by Django 4.0.10 on 2024-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
