# Generated by Django 4.0.10 on 2024-03-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_input_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedpoem',
            old_name='input_id',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='generatedpoem',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='user_id',
            new_name='user',
        ),
    ]
